services:
  bookseerr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookseerr
    restart: unless-stopped
    ports:
      - "5057:3000"
    env_file:
      - ./.env
    volumes:
      # Use a named volume for the database to avoid host permission issues
      - bookseerr_data:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy_default

# Define the named volume
volumes:
  bookseerr_data:

networks:
  proxy_default:
    external: true
